### PR TITLE
rename torch extras and defines

### PR DESCRIPTION
**Pull request by lyskov**
Current Rosetta `pytorch` and `pytorch_gpu` extras are misnomers since we do link to `libtorch` and not to `pytorch`. This PR address this.

### CODE REVIEW

**Review by MoritzErtelt — APPROVED** [review]
Looks good to me, that should avoid confusion 👍

**Comment by roccomoretti** [comment]
One concern here would be the documentation and publication issues -- Is there a clear path for people who have used `extras=pytorch` and who are running scripts which explicitly reference `rosetta_scripts.pytorch.linuxgccrelease` going to be able to easily discover why those commands are no longer working?

**Comment by lyskov** [comment]
@MoritzErtelt this is now merged, could you please update the relevant docs? Thanks,

**Comment by MoritzErtelt** [comment]
Sure, I've updated the documentation 👍

**Pull request merged**
