### PR TITLE
fix(DAlphaBall make): Avoid duplicate symbols linker error

### PR DESCRIPTION
**Pull request by rebelot**
Declare-only gmp globals in header file and define them in only one source file

### CODE REVIEW

**Review by roccomoretti — APPROVED** [review]
Looks fine to me.

@rebelot Could you please sign the Rosetta Contributor Licensing Agreement  at https://www.rosettacommons.org/forms/cla ? (See https://github.com/RosettaCommons/rosetta/blob/main/CONTRIBUTING.md for more info.)

**Comment by rebelot** [comment]
> @rebelot Could you please sign the Rosetta Contributor Licensing Agreement at https://www.rosettacommons.org/forms/cla ? (See https://github.com/RosettaCommons/rosetta/blob/main/CONTRIBUTING.md for more info.)

signed 👌

**Comment by ajasja** [comment]
@roccomoretti Who are the people with the magic merge powers? I think we should aim to have as little open PRs as possible...

**Comment by roccomoretti** [comment]
They're the @can_merge_to_main team. (And should be able to be pinged as such.)

Agreed that we want to minimize the number of open PRs. This one unfortunately slipped through the cracks. (Sorry @rebelot.)

**Pull request merged**
